// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExternalList.proto

package com.ykt.im.socket.protobuf;

public final class ExternalListWrap {
  private ExternalListWrap() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExternalListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.ExternalList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *客户userid数组
     * </pre>
     *
     * <code>repeated string external_userid = 1;</code>
     */
    java.util.List<java.lang.String>
        getExternalUseridList();
    /**
     * <pre>
     *客户userid数组
     * </pre>
     *
     * <code>repeated string external_userid = 1;</code>
     */
    int getExternalUseridCount();
    /**
     * <pre>
     *客户userid数组
     * </pre>
     *
     * <code>repeated string external_userid = 1;</code>
     */
    java.lang.String getExternalUserid(int index);
    /**
     * <pre>
     *客户userid数组
     * </pre>
     *
     * <code>repeated string external_userid = 1;</code>
     */
    com.google.protobuf.ByteString
        getExternalUseridBytes(int index);
  }
  /**
   * Protobuf type {@code protocol.ExternalList}
   */
  public  static final class ExternalList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.ExternalList)
      ExternalListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExternalList.newBuilder() to construct.
    private ExternalList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExternalList() {
      externalUserid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExternalList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                externalUserid_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              externalUserid_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          externalUserid_ = externalUserid_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ykt.im.socket.protobuf.ExternalListWrap.internal_static_protocol_ExternalList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ykt.im.socket.protobuf.ExternalListWrap.internal_static_protocol_ExternalList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList.class, com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList.Builder.class);
    }

    public static final int EXTERNAL_USERID_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList externalUserid_;
    /**
     * <pre>
     *客户userid数组
     * </pre>
     *
     * <code>repeated string external_userid = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getExternalUseridList() {
      return externalUserid_;
    }
    /**
     * <pre>
     *客户userid数组
     * </pre>
     *
     * <code>repeated string external_userid = 1;</code>
     */
    public int getExternalUseridCount() {
      return externalUserid_.size();
    }
    /**
     * <pre>
     *客户userid数组
     * </pre>
     *
     * <code>repeated string external_userid = 1;</code>
     */
    public java.lang.String getExternalUserid(int index) {
      return externalUserid_.get(index);
    }
    /**
     * <pre>
     *客户userid数组
     * </pre>
     *
     * <code>repeated string external_userid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getExternalUseridBytes(int index) {
      return externalUserid_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < externalUserid_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, externalUserid_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < externalUserid_.size(); i++) {
          dataSize += computeStringSizeNoTag(externalUserid_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getExternalUseridList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList)) {
        return super.equals(obj);
      }
      com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList other = (com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList) obj;

      if (!getExternalUseridList()
          .equals(other.getExternalUseridList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getExternalUseridCount() > 0) {
        hash = (37 * hash) + EXTERNAL_USERID_FIELD_NUMBER;
        hash = (53 * hash) + getExternalUseridList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ExternalList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.ExternalList)
        com.ykt.im.socket.protobuf.ExternalListWrap.ExternalListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ykt.im.socket.protobuf.ExternalListWrap.internal_static_protocol_ExternalList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ykt.im.socket.protobuf.ExternalListWrap.internal_static_protocol_ExternalList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList.class, com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList.Builder.class);
      }

      // Construct using com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        externalUserid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ykt.im.socket.protobuf.ExternalListWrap.internal_static_protocol_ExternalList_descriptor;
      }

      @java.lang.Override
      public com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList getDefaultInstanceForType() {
        return com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList.getDefaultInstance();
      }

      @java.lang.Override
      public com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList build() {
        com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList buildPartial() {
        com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList result = new com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          externalUserid_ = externalUserid_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.externalUserid_ = externalUserid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList) {
          return mergeFrom((com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList other) {
        if (other == com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList.getDefaultInstance()) return this;
        if (!other.externalUserid_.isEmpty()) {
          if (externalUserid_.isEmpty()) {
            externalUserid_ = other.externalUserid_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureExternalUseridIsMutable();
            externalUserid_.addAll(other.externalUserid_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList externalUserid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureExternalUseridIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          externalUserid_ = new com.google.protobuf.LazyStringArrayList(externalUserid_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       *客户userid数组
       * </pre>
       *
       * <code>repeated string external_userid = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getExternalUseridList() {
        return externalUserid_.getUnmodifiableView();
      }
      /**
       * <pre>
       *客户userid数组
       * </pre>
       *
       * <code>repeated string external_userid = 1;</code>
       */
      public int getExternalUseridCount() {
        return externalUserid_.size();
      }
      /**
       * <pre>
       *客户userid数组
       * </pre>
       *
       * <code>repeated string external_userid = 1;</code>
       */
      public java.lang.String getExternalUserid(int index) {
        return externalUserid_.get(index);
      }
      /**
       * <pre>
       *客户userid数组
       * </pre>
       *
       * <code>repeated string external_userid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getExternalUseridBytes(int index) {
        return externalUserid_.getByteString(index);
      }
      /**
       * <pre>
       *客户userid数组
       * </pre>
       *
       * <code>repeated string external_userid = 1;</code>
       */
      public Builder setExternalUserid(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureExternalUseridIsMutable();
        externalUserid_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户userid数组
       * </pre>
       *
       * <code>repeated string external_userid = 1;</code>
       */
      public Builder addExternalUserid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureExternalUseridIsMutable();
        externalUserid_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户userid数组
       * </pre>
       *
       * <code>repeated string external_userid = 1;</code>
       */
      public Builder addAllExternalUserid(
          java.lang.Iterable<java.lang.String> values) {
        ensureExternalUseridIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, externalUserid_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户userid数组
       * </pre>
       *
       * <code>repeated string external_userid = 1;</code>
       */
      public Builder clearExternalUserid() {
        externalUserid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户userid数组
       * </pre>
       *
       * <code>repeated string external_userid = 1;</code>
       */
      public Builder addExternalUseridBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureExternalUseridIsMutable();
        externalUserid_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.ExternalList)
    }

    // @@protoc_insertion_point(class_scope:protocol.ExternalList)
    private static final com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList();
    }

    public static com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExternalList>
        PARSER = new com.google.protobuf.AbstractParser<ExternalList>() {
      @java.lang.Override
      public ExternalList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExternalList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExternalList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExternalList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ykt.im.socket.protobuf.ExternalListWrap.ExternalList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ExternalList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_ExternalList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ExternalList.proto\022\010protocol\"\'\n\014Extern" +
      "alList\022\027\n\017external_userid\030\001 \003(\tB0\n\032com.y" +
      "kt.im.socket.protobufB\020ExternalListWrapH" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_ExternalList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_ExternalList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_ExternalList_descriptor,
        new java.lang.String[] { "ExternalUserid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
