// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExternalMsg.proto

package com.ykt.im.socket.protobuf;

public final class ExternalMsgWrap {
  private ExternalMsgWrap() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExternalMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.ExternalMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *客户userid
     * </pre>
     *
     * <code>string external_userid = 1;</code>
     */
    java.lang.String getExternalUserid();
    /**
     * <pre>
     *客户userid
     * </pre>
     *
     * <code>string external_userid = 1;</code>
     */
    com.google.protobuf.ByteString
        getExternalUseridBytes();

    /**
     * <pre>
     *客户端消息ID
     * </pre>
     *
     * <code>string wx_msg_id = 2;</code>
     */
    java.lang.String getWxMsgId();
    /**
     * <pre>
     *客户端消息ID
     * </pre>
     *
     * <code>string wx_msg_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getWxMsgIdBytes();

    /**
     * <pre>
     *消息类型（0：普通文字消息，1：图片消息，2：收藏，3：语音消息，4：视频消息，5：红包，6：微文档，7：文件消息，8位置，9：个人名片）
     * </pre>
     *
     * <code>int32 msg_type = 3;</code>
     */
    int getMsgType();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string msg_content = 4;</code>
     */
    java.lang.String getMsgContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string msg_content = 4;</code>
     */
    com.google.protobuf.ByteString
        getMsgContentBytes();

    /**
     * <pre>
     *客户端消息时间(格式:2020-06-28 12:24:30)
     * </pre>
     *
     * <code>string wx_msg_time = 5;</code>
     */
    java.lang.String getWxMsgTime();
    /**
     * <pre>
     *客户端消息时间(格式:2020-06-28 12:24:30)
     * </pre>
     *
     * <code>string wx_msg_time = 5;</code>
     */
    com.google.protobuf.ByteString
        getWxMsgTimeBytes();
  }
  /**
   * Protobuf type {@code protocol.ExternalMsg}
   */
  public  static final class ExternalMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.ExternalMsg)
      ExternalMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExternalMsg.newBuilder() to construct.
    private ExternalMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExternalMsg() {
      externalUserid_ = "";
      wxMsgId_ = "";
      msgContent_ = "";
      wxMsgTime_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExternalMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              externalUserid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              wxMsgId_ = s;
              break;
            }
            case 24: {

              msgType_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              msgContent_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              wxMsgTime_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ykt.im.socket.protobuf.ExternalMsgWrap.internal_static_protocol_ExternalMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ykt.im.socket.protobuf.ExternalMsgWrap.internal_static_protocol_ExternalMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg.class, com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg.Builder.class);
    }

    public static final int EXTERNAL_USERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object externalUserid_;
    /**
     * <pre>
     *客户userid
     * </pre>
     *
     * <code>string external_userid = 1;</code>
     */
    public java.lang.String getExternalUserid() {
      java.lang.Object ref = externalUserid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalUserid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *客户userid
     * </pre>
     *
     * <code>string external_userid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getExternalUseridBytes() {
      java.lang.Object ref = externalUserid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalUserid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WX_MSG_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object wxMsgId_;
    /**
     * <pre>
     *客户端消息ID
     * </pre>
     *
     * <code>string wx_msg_id = 2;</code>
     */
    public java.lang.String getWxMsgId() {
      java.lang.Object ref = wxMsgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wxMsgId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *客户端消息ID
     * </pre>
     *
     * <code>string wx_msg_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getWxMsgIdBytes() {
      java.lang.Object ref = wxMsgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wxMsgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 3;
    private int msgType_;
    /**
     * <pre>
     *消息类型（0：普通文字消息，1：图片消息，2：收藏，3：语音消息，4：视频消息，5：红包，6：微文档，7：文件消息，8位置，9：个人名片）
     * </pre>
     *
     * <code>int32 msg_type = 3;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int MSG_CONTENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object msgContent_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string msg_content = 4;</code>
     */
    public java.lang.String getMsgContent() {
      java.lang.Object ref = msgContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgContent_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string msg_content = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMsgContentBytes() {
      java.lang.Object ref = msgContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WX_MSG_TIME_FIELD_NUMBER = 5;
    private volatile java.lang.Object wxMsgTime_;
    /**
     * <pre>
     *客户端消息时间(格式:2020-06-28 12:24:30)
     * </pre>
     *
     * <code>string wx_msg_time = 5;</code>
     */
    public java.lang.String getWxMsgTime() {
      java.lang.Object ref = wxMsgTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wxMsgTime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *客户端消息时间(格式:2020-06-28 12:24:30)
     * </pre>
     *
     * <code>string wx_msg_time = 5;</code>
     */
    public com.google.protobuf.ByteString
        getWxMsgTimeBytes() {
      java.lang.Object ref = wxMsgTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wxMsgTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getExternalUseridBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, externalUserid_);
      }
      if (!getWxMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, wxMsgId_);
      }
      if (msgType_ != 0) {
        output.writeInt32(3, msgType_);
      }
      if (!getMsgContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msgContent_);
      }
      if (!getWxMsgTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, wxMsgTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getExternalUseridBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, externalUserid_);
      }
      if (!getWxMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, wxMsgId_);
      }
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, msgType_);
      }
      if (!getMsgContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msgContent_);
      }
      if (!getWxMsgTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, wxMsgTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg)) {
        return super.equals(obj);
      }
      com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg other = (com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg) obj;

      if (!getExternalUserid()
          .equals(other.getExternalUserid())) return false;
      if (!getWxMsgId()
          .equals(other.getWxMsgId())) return false;
      if (getMsgType()
          != other.getMsgType()) return false;
      if (!getMsgContent()
          .equals(other.getMsgContent())) return false;
      if (!getWxMsgTime()
          .equals(other.getWxMsgTime())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXTERNAL_USERID_FIELD_NUMBER;
      hash = (53 * hash) + getExternalUserid().hashCode();
      hash = (37 * hash) + WX_MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + getWxMsgId().hashCode();
      hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + MSG_CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getMsgContent().hashCode();
      hash = (37 * hash) + WX_MSG_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getWxMsgTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ExternalMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.ExternalMsg)
        com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ykt.im.socket.protobuf.ExternalMsgWrap.internal_static_protocol_ExternalMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ykt.im.socket.protobuf.ExternalMsgWrap.internal_static_protocol_ExternalMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg.class, com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg.Builder.class);
      }

      // Construct using com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        externalUserid_ = "";

        wxMsgId_ = "";

        msgType_ = 0;

        msgContent_ = "";

        wxMsgTime_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ykt.im.socket.protobuf.ExternalMsgWrap.internal_static_protocol_ExternalMsg_descriptor;
      }

      @java.lang.Override
      public com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg getDefaultInstanceForType() {
        return com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg build() {
        com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg buildPartial() {
        com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg result = new com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg(this);
        result.externalUserid_ = externalUserid_;
        result.wxMsgId_ = wxMsgId_;
        result.msgType_ = msgType_;
        result.msgContent_ = msgContent_;
        result.wxMsgTime_ = wxMsgTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg) {
          return mergeFrom((com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg other) {
        if (other == com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg.getDefaultInstance()) return this;
        if (!other.getExternalUserid().isEmpty()) {
          externalUserid_ = other.externalUserid_;
          onChanged();
        }
        if (!other.getWxMsgId().isEmpty()) {
          wxMsgId_ = other.wxMsgId_;
          onChanged();
        }
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (!other.getMsgContent().isEmpty()) {
          msgContent_ = other.msgContent_;
          onChanged();
        }
        if (!other.getWxMsgTime().isEmpty()) {
          wxMsgTime_ = other.wxMsgTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object externalUserid_ = "";
      /**
       * <pre>
       *客户userid
       * </pre>
       *
       * <code>string external_userid = 1;</code>
       */
      public java.lang.String getExternalUserid() {
        java.lang.Object ref = externalUserid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          externalUserid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *客户userid
       * </pre>
       *
       * <code>string external_userid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getExternalUseridBytes() {
        java.lang.Object ref = externalUserid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          externalUserid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *客户userid
       * </pre>
       *
       * <code>string external_userid = 1;</code>
       */
      public Builder setExternalUserid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        externalUserid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户userid
       * </pre>
       *
       * <code>string external_userid = 1;</code>
       */
      public Builder clearExternalUserid() {
        
        externalUserid_ = getDefaultInstance().getExternalUserid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户userid
       * </pre>
       *
       * <code>string external_userid = 1;</code>
       */
      public Builder setExternalUseridBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        externalUserid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object wxMsgId_ = "";
      /**
       * <pre>
       *客户端消息ID
       * </pre>
       *
       * <code>string wx_msg_id = 2;</code>
       */
      public java.lang.String getWxMsgId() {
        java.lang.Object ref = wxMsgId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          wxMsgId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *客户端消息ID
       * </pre>
       *
       * <code>string wx_msg_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getWxMsgIdBytes() {
        java.lang.Object ref = wxMsgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          wxMsgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *客户端消息ID
       * </pre>
       *
       * <code>string wx_msg_id = 2;</code>
       */
      public Builder setWxMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        wxMsgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端消息ID
       * </pre>
       *
       * <code>string wx_msg_id = 2;</code>
       */
      public Builder clearWxMsgId() {
        
        wxMsgId_ = getDefaultInstance().getWxMsgId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端消息ID
       * </pre>
       *
       * <code>string wx_msg_id = 2;</code>
       */
      public Builder setWxMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        wxMsgId_ = value;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <pre>
       *消息类型（0：普通文字消息，1：图片消息，2：收藏，3：语音消息，4：视频消息，5：红包，6：微文档，7：文件消息，8位置，9：个人名片）
       * </pre>
       *
       * <code>int32 msg_type = 3;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <pre>
       *消息类型（0：普通文字消息，1：图片消息，2：收藏，3：语音消息，4：视频消息，5：红包，6：微文档，7：文件消息，8位置，9：个人名片）
       * </pre>
       *
       * <code>int32 msg_type = 3;</code>
       */
      public Builder setMsgType(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型（0：普通文字消息，1：图片消息，2：收藏，3：语音消息，4：视频消息，5：红包，6：微文档，7：文件消息，8位置，9：个人名片）
       * </pre>
       *
       * <code>int32 msg_type = 3;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msgContent_ = "";
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string msg_content = 4;</code>
       */
      public java.lang.String getMsgContent() {
        java.lang.Object ref = msgContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string msg_content = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMsgContentBytes() {
        java.lang.Object ref = msgContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string msg_content = 4;</code>
       */
      public Builder setMsgContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string msg_content = 4;</code>
       */
      public Builder clearMsgContent() {
        
        msgContent_ = getDefaultInstance().getMsgContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string msg_content = 4;</code>
       */
      public Builder setMsgContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgContent_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object wxMsgTime_ = "";
      /**
       * <pre>
       *客户端消息时间(格式:2020-06-28 12:24:30)
       * </pre>
       *
       * <code>string wx_msg_time = 5;</code>
       */
      public java.lang.String getWxMsgTime() {
        java.lang.Object ref = wxMsgTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          wxMsgTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *客户端消息时间(格式:2020-06-28 12:24:30)
       * </pre>
       *
       * <code>string wx_msg_time = 5;</code>
       */
      public com.google.protobuf.ByteString
          getWxMsgTimeBytes() {
        java.lang.Object ref = wxMsgTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          wxMsgTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *客户端消息时间(格式:2020-06-28 12:24:30)
       * </pre>
       *
       * <code>string wx_msg_time = 5;</code>
       */
      public Builder setWxMsgTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        wxMsgTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端消息时间(格式:2020-06-28 12:24:30)
       * </pre>
       *
       * <code>string wx_msg_time = 5;</code>
       */
      public Builder clearWxMsgTime() {
        
        wxMsgTime_ = getDefaultInstance().getWxMsgTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端消息时间(格式:2020-06-28 12:24:30)
       * </pre>
       *
       * <code>string wx_msg_time = 5;</code>
       */
      public Builder setWxMsgTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        wxMsgTime_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.ExternalMsg)
    }

    // @@protoc_insertion_point(class_scope:protocol.ExternalMsg)
    private static final com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg();
    }

    public static com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExternalMsg>
        PARSER = new com.google.protobuf.AbstractParser<ExternalMsg>() {
      @java.lang.Override
      public ExternalMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExternalMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExternalMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExternalMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ykt.im.socket.protobuf.ExternalMsgWrap.ExternalMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ExternalMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_ExternalMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ExternalMsg.proto\022\010protocol\"u\n\013Externa" +
      "lMsg\022\027\n\017external_userid\030\001 \001(\t\022\021\n\twx_msg_" +
      "id\030\002 \001(\t\022\020\n\010msg_type\030\003 \001(\005\022\023\n\013msg_conten" +
      "t\030\004 \001(\t\022\023\n\013wx_msg_time\030\005 \001(\tB/\n\032com.ykt." +
      "im.socket.protobufB\017ExternalMsgWrapH\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_ExternalMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_ExternalMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_ExternalMsg_descriptor,
        new java.lang.String[] { "ExternalUserid", "WxMsgId", "MsgType", "MsgContent", "WxMsgTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
