# 配置端口
server:
  port: 18080
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  # 配置数据源
  datasource:
    druid:
      first:
        url: jdbc:mysql://192.168.1.250:3306/wx-work-im?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456789
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        # 初始化时建立物理连接的个数
        initial-size: 10
        # 最小连接池连接数量，最小空闲数量
        min-idle: 10
        # 最大连接池连接数量，最大活跃连接数
        max-active: 100
        # 配置获取连接等待超时的时间
        max-wait: 5000
        filter:
          stat:
            enabled: true
        # stat是统计，wall是SQL防火墙，防SQL注入的，log4j是用来输出统计数据的
        filters: stat,wall,slf4j
        #慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # druid监控页面配置
      stat-view-servlet:
        ## 是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
        enabled: true
        # 禁止手动重置监控数据
        reset-enable: false
        # 设置监控页面的登录名和密码
        login-username: root
        login-password: root
        #白名单
        allow:
        #黑名单（优先）
        deny: 
        url-pattern: /druid/*
      # druid监控页面过滤器
      web-stat-filter:
        enabled: true

  redis:
    database: 0
    #单机模式
    host: 127.0.0.1
    port: 6379
    password: redis
    #jedis:
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 1
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      # 全局逻辑删除的实体字段名
      logic-delete-field: deleted
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置扫描通用枚举
  #支持通配符 * 或者 ; 分割
  typeEnumsPackage: com.ykt.im.common.enums


#自定义配置
customize:
  #时间格式yyyy-MM-dd HH:mm:ss.SSS
  date-time-format: yyyy-MM-dd HH:mm:ss
  #时区
  time-zone: GMT+8
  #最大分页
  pagination: 1000

  #ID生成器,集群时每个部署节点唯一
  #机器ID:可用范围(1-31)
  worker-id: 1
  #机房ID:可用范围(1-31)
  data-center-id: 1

  #cookie加密密钥
  cookie-encrypt-key: qwertyui12345678!@#$%^&*
  #cookie过期时间(单位:小时)
  cookie-max-age: 12
  #Redis缓存过期时间(单位:分钟)
  redis-duration: 1440
  #短信验证服务域名
  cloud-domain: http://192.168.1.151:9091
  #上传图片格式
  pic-type:
    - jpeg
    - jpg
    - flv
    - bmp
    - png
    - gif

  #7牛OSS配置
  oss:
    #cdn地址
    cdn-path: http://qblwz6n4f.bkt.clouddn.com
    #oss账户ID
    accesskey-id: g40gJeE6Dpy9zY5klpaqGVxK6lUYhy-cikrpzdLW
    #oss账户秘钥
    accesskey-secret: F_vMVt_Iza5LzUbySjHoImnOu3cqZV-uRXCeCrfv
    #oss桶名
    bucket-name: nfsc
    #oss文件存储路径,/结尾
    file-path: wx-work-im/pic/
    #机房 0华东	1华北 2华南 3北美 4东南亚
    region: 2

#socket配置
web-socket:
  port: 38081
socket:
  port: 38082